name: Publish python package

on:
  workflow_dispatch:
    inputs:
      package:
        description: package name
        type: choice
        options: [eyes_universal, eyes_selenium, eyes_robotframework]
        required: true
      version:
        description: version increment type
        type: choice
        options: [patch, minor, major]
        required: true

jobs:

  test:
    uses: ikseek/test_actions/.github/workflows/test.yml@main
    with:
      releasing_package: hot
