name: Build and test python packages
on:
  schedule: [ cron: 17 3 * * * ]
  pull_request:
  workflow_dispatch:
    inputs:
      unit:
        description: Unit tests
        type: boolean
        required: false
        default: false

  workflow_call:
    inputs:
      unit:
        description: Unit tests
        type: boolean
        required: false
        default: true
      releasing_package:
        description: name of the package being released
        required: false
        type: string

jobs:
  test_vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(inputs) }}"
      - run: echo "${{ toJson(github) }}"
      
  test_needs:
    runs-on: ubuntu-latest
    needs: test_vars
    steps:
      - run: echo "${{ toJson(inputs) }}"
      - run: echo "${{ toJson(github) }}"
      - run: echo "${{ toJson(needs) }}"
