name: Build and test python packages
on:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      releasing_package:
        description: name of the package being released
        required: false
        type: string

jobs:
  test_vars:
    runs-on: ubuntu-latest
    steps:
      - run: env
    env:
     PACKAGE_NAME_GIVEN: ${{ inputs.releasing_package && 'given' || 'notgiven'}}
     PACKAGE_NAME_IN_LIST: ${{ contains('hot, bananas', inputs.releasing_package) }}
     PACKAGE_NAME_ITSELF: ${{ inputs.releasing_package }}
