name: Build and test python packages
on:
  pull_request:
  workflow_dispatch:
    inputs:
      unit:
        description: Unit tests
        type: boolean
        required: false

  workflow_call:
    inputs:
      releasing_package:
        description: name of the package being released
        required: false
        type: string

jobs:
  test_vars:
    runs-on: ubuntu-latest
    steps:
      - run: env
    env:
     PACKAGE_NAME_GIVEN: ${{ inputs.releasing_package && 'given' || 'notgiven'}}
     PACKAGE_NAME_IS_NULL: ${{ inputs.releasing_package == null }}
     PACKAGE_NAME_IN_LIST: ${{ contains('hot, bananas', inputs.releasing_package) }}
     PACKAGE_NAME_IS_HOT_OR_BANANAS: ${{ inputs.releasing_package == 'hot' || inputs.releasing_package == 'bananas' }}
     PACKAGE_NAME_ITSELF: ${{ inputs.releasing_package }}

  test_vars2:
    runs-on: ubuntu-latest
    if: github.event.input.unit
    steps:
      - run: env
    env:
     PACKAGE_NAME_GIVEN: ${{ inputs.releasing_package && 'given' || 'notgiven'}}
     PACKAGE_NAME_IS_NULL: ${{ inputs.releasing_package == null }}
     PACKAGE_NAME_IN_LIST: ${{ contains('hot, bananas', inputs.releasing_package) }}
     PACKAGE_NAME_IS_HOT_OR_BANANAS: ${{ inputs.releasing_package == 'hot' || inputs.releasing_package == 'bananas' }}
     PACKAGE_NAME_ITSELF: ${{ inputs.releasing_package }}
